backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
collections:
  - name: "posts"
    label: "Blog"
    folder: "website-church/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Texto de articulo", name: "body", widget: "markdown" }

  
